// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


var App = 0;

var BrowserWeb3Capabilities = 0;

var ThreeBox = 0;

exports.App = App;
exports.BrowserWeb3Capabilities = BrowserWeb3Capabilities;
exports.ThreeBox = ThreeBox;
/* No side effect */
